# Generated by Django 5.0.3 on 2024-03-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visiable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
