# Generated by Django 5.0.3 on 2024-03-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_visiable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visiable',
        ),
        migrations.AddField(
            model_name='product',
            name='visiable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
