# Generated by Django 5.0.3 on 2024-03-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_comment_visiable_product_visiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='visiable',
            field=models.BooleanField(default=True),
        ),
    ]
